
---
- name: Download vault archive Linux 32 bits
  get_url:
    url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_386.zip
    dest: /tmp/vault-{{vault_version}}.zip
  when: "'32' in ansible_architecture and 'Linux' == ansible_system"

- name: Download vault archive Linux 64 bits
  get_url:
    url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_386.zip
    dest: /tmp/vault-{{vault_version}}.zip
  when: "'64' in ansible_architecture and 'Linux' == ansible_system"
